version: "3"
services:
  parser:
    restart: always
    build:
      context: ./pmparser
      dockerfile: app.dockerfile
    env_file:
      - ./pmparser/.env
    volumes:
      - ./parser.log:/application/parser.log
    ports:
      - 5000:5000
      # - 9999:9999
  db:
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - 5001:5432
  # request_handler:
  #   restart: always
  #   build:
  #     context: ./backend/
  #     dockerfile: req.dockerfile
  #   env_file:
  #     - ./backend/.env
  #   volumes:
  #     - ./requestHandler.log:/application/requestHandler.log
  #   ports:
  #     - 5004:5004

