version: "3"
services:
  parser:
    hostname: pmparser.ru
    restart: always
    build:
      context: ./pmparser
      dockerfile: app.dockerfile
    env_file:
      - ./pmparser/.env
    volumes:
      - ./parser.log:/application/parser.log
    ports:
      - 5000:5000
  db:
    hostname: pmdb.ru
    restart: always
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/001.sql
    # expose:
    #   - 5001:5432
    ports:
      - 5001:5432

