// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.1
// source: app/protos/categories.proto

package parser

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RootCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
}

func (x *RootCategoriesRequest) Reset() {
	*x = RootCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootCategoriesRequest) ProtoMessage() {}

func (x *RootCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootCategoriesRequest.ProtoReflect.Descriptor instead.
func (*RootCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{0}
}

func (x *RootCategoriesRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

type SubCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market      Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
	CategoryUrl string  `protobuf:"bytes,2,opt,name=categoryUrl,proto3" json:"categoryUrl,omitempty"`
}

func (x *SubCategoriesRequest) Reset() {
	*x = SubCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoriesRequest) ProtoMessage() {}

func (x *SubCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoriesRequest.ProtoReflect.Descriptor instead.
func (*SubCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{1}
}

func (x *SubCategoriesRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

func (x *SubCategoriesRequest) GetCategoryUrl() string {
	if x != nil {
		return x.CategoryUrl
	}
	return ""
}

type CategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*CategoryResponse_Category
	//	*CategoryResponse_Status
	Message isCategoryResponse_Message `protobuf_oneof:"message"`
}

func (x *CategoryResponse) Reset() {
	*x = CategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResponse) ProtoMessage() {}

func (x *CategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResponse.ProtoReflect.Descriptor instead.
func (*CategoryResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{2}
}

func (m *CategoryResponse) GetMessage() isCategoryResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *CategoryResponse) GetCategory() *Category {
	if x, ok := x.GetMessage().(*CategoryResponse_Category); ok {
		return x.Category
	}
	return nil
}

func (x *CategoryResponse) GetStatus() *status.Status {
	if x, ok := x.GetMessage().(*CategoryResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isCategoryResponse_Message interface {
	isCategoryResponse_Message()
}

type CategoryResponse_Category struct {
	Category *Category `protobuf:"bytes,1,opt,name=category,proto3,oneof"`
}

type CategoryResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*CategoryResponse_Category) isCategoryResponse_Message() {}

func (*CategoryResponse_Status) isCategoryResponse_Message() {}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url       string  `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ParentUrl *string `protobuf:"bytes,3,opt,name=parentUrl,proto3,oneof" json:"parentUrl,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Category) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Category) GetParentUrl() string {
	if x != nil && x.ParentUrl != nil {
		return *x.ParentUrl
	}
	return ""
}

type FiltersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market      Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
	CategoryUrl string  `protobuf:"bytes,2,opt,name=categoryUrl,proto3" json:"categoryUrl,omitempty"`
}

func (x *FiltersRequest) Reset() {
	*x = FiltersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiltersRequest) ProtoMessage() {}

func (x *FiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiltersRequest.ProtoReflect.Descriptor instead.
func (*FiltersRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{4}
}

func (x *FiltersRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

func (x *FiltersRequest) GetCategoryUrl() string {
	if x != nil {
		return x.CategoryUrl
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*FilterResponse_Filter
	//	*FilterResponse_Status
	Message isFilterResponse_Message `protobuf_oneof:"message"`
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{5}
}

func (m *FilterResponse) GetMessage() isFilterResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *FilterResponse) GetFilter() *Filter {
	if x, ok := x.GetMessage().(*FilterResponse_Filter); ok {
		return x.Filter
	}
	return nil
}

func (x *FilterResponse) GetStatus() *status.Status {
	if x, ok := x.GetMessage().(*FilterResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isFilterResponse_Message interface {
	isFilterResponse_Message()
}

type FilterResponse_Filter struct {
	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof"`
}

type FilterResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*FilterResponse_Filter) isFilterResponse_Message() {}

func (*FilterResponse_Status) isFilterResponse_Message() {}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Key          string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExternalType string  `protobuf:"bytes,3,opt,name=externalType,proto3" json:"externalType,omitempty"`
	InternalType Filters `protobuf:"varint,4,opt,name=internalType,proto3,enum=app.protos.Filters" json:"internalType,omitempty"`
	// Types that are assignable to Data:
	//	*Filter_RangeFilter
	//	*Filter_SelectionFilter
	//	*Filter_BoolFilter
	Data isFilter_Data `protobuf_oneof:"data"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_categories_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_categories_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_app_protos_categories_proto_rawDescGZIP(), []int{6}
}

func (x *Filter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetExternalType() string {
	if x != nil {
		return x.ExternalType
	}
	return ""
}

func (x *Filter) GetInternalType() Filters {
	if x != nil {
		return x.InternalType
	}
	return Filters_RANGE
}

func (m *Filter) GetData() isFilter_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Filter) GetRangeFilter() *RangeFilter {
	if x, ok := x.GetData().(*Filter_RangeFilter); ok {
		return x.RangeFilter
	}
	return nil
}

func (x *Filter) GetSelectionFilter() *SelectionFilter {
	if x, ok := x.GetData().(*Filter_SelectionFilter); ok {
		return x.SelectionFilter
	}
	return nil
}

func (x *Filter) GetBoolFilter() *BoolFilter {
	if x, ok := x.GetData().(*Filter_BoolFilter); ok {
		return x.BoolFilter
	}
	return nil
}

type isFilter_Data interface {
	isFilter_Data()
}

type Filter_RangeFilter struct {
	RangeFilter *RangeFilter `protobuf:"bytes,5,opt,name=rangeFilter,proto3,oneof"`
}

type Filter_SelectionFilter struct {
	SelectionFilter *SelectionFilter `protobuf:"bytes,6,opt,name=selectionFilter,proto3,oneof"`
}

type Filter_BoolFilter struct {
	BoolFilter *BoolFilter `protobuf:"bytes,7,opt,name=boolFilter,proto3,oneof"`
}

func (*Filter_RangeFilter) isFilter_Data() {}

func (*Filter_SelectionFilter) isFilter_Data() {}

func (*Filter_BoolFilter) isFilter_Data() {}

var File_app_protos_categories_proto protoreflect.FileDescriptor

var file_app_protos_categories_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x15, 0x52, 0x6f,
	0x6f, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x22, 0x65, 0x0a, 0x14, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x06, 0x6d,
	0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x7f, 0x0a, 0x10, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x48, 0x00, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x63, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x21, 0x0a, 0x09,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x88, 0x01, 0x01, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x5f, 0x0a,
	0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x55, 0x72, 0x6c, 0x22, 0x77,
	0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2c,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd5, 0x02, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x37,
	0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x38, 0x0a,
	0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x62, 0x6f, 0x6f,
	0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x8e, 0x02, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x61, 0x72, 0x73,
	0x65, 0x72, 0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x62, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20,
	0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x62, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x12, 0x4e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01,
	0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_protos_categories_proto_rawDescOnce sync.Once
	file_app_protos_categories_proto_rawDescData = file_app_protos_categories_proto_rawDesc
)

func file_app_protos_categories_proto_rawDescGZIP() []byte {
	file_app_protos_categories_proto_rawDescOnce.Do(func() {
		file_app_protos_categories_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protos_categories_proto_rawDescData)
	})
	return file_app_protos_categories_proto_rawDescData
}

var file_app_protos_categories_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_protos_categories_proto_goTypes = []interface{}{
	(*RootCategoriesRequest)(nil), // 0: app.protos.RootCategoriesRequest
	(*SubCategoriesRequest)(nil),  // 1: app.protos.SubCategoriesRequest
	(*CategoryResponse)(nil),      // 2: app.protos.CategoryResponse
	(*Category)(nil),              // 3: app.protos.Category
	(*FiltersRequest)(nil),        // 4: app.protos.FiltersRequest
	(*FilterResponse)(nil),        // 5: app.protos.FilterResponse
	(*Filter)(nil),                // 6: app.protos.Filter
	(Markets)(0),                  // 7: app.protos.Markets
	(*status.Status)(nil),         // 8: google.rpc.Status
	(Filters)(0),                  // 9: app.protos.Filters
	(*RangeFilter)(nil),           // 10: app.protos.RangeFilter
	(*SelectionFilter)(nil),       // 11: app.protos.SelectionFilter
	(*BoolFilter)(nil),            // 12: app.protos.BoolFilter
}
var file_app_protos_categories_proto_depIdxs = []int32{
	7,  // 0: app.protos.RootCategoriesRequest.market:type_name -> app.protos.Markets
	7,  // 1: app.protos.SubCategoriesRequest.market:type_name -> app.protos.Markets
	3,  // 2: app.protos.CategoryResponse.category:type_name -> app.protos.Category
	8,  // 3: app.protos.CategoryResponse.status:type_name -> google.rpc.Status
	7,  // 4: app.protos.FiltersRequest.market:type_name -> app.protos.Markets
	6,  // 5: app.protos.FilterResponse.filter:type_name -> app.protos.Filter
	8,  // 6: app.protos.FilterResponse.status:type_name -> google.rpc.Status
	9,  // 7: app.protos.Filter.internalType:type_name -> app.protos.Filters
	10, // 8: app.protos.Filter.rangeFilter:type_name -> app.protos.RangeFilter
	11, // 9: app.protos.Filter.selectionFilter:type_name -> app.protos.SelectionFilter
	12, // 10: app.protos.Filter.boolFilter:type_name -> app.protos.BoolFilter
	0,  // 11: app.protos.CategoryParser.GetRootCategories:input_type -> app.protos.RootCategoriesRequest
	1,  // 12: app.protos.CategoryParser.GetSubCategories:input_type -> app.protos.SubCategoriesRequest
	4,  // 13: app.protos.CategoryParser.GetCategoryFilters:input_type -> app.protos.FiltersRequest
	2,  // 14: app.protos.CategoryParser.GetRootCategories:output_type -> app.protos.CategoryResponse
	2,  // 15: app.protos.CategoryParser.GetSubCategories:output_type -> app.protos.CategoryResponse
	5,  // 16: app.protos.CategoryParser.GetCategoryFilters:output_type -> app.protos.FilterResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_app_protos_categories_proto_init() }
func file_app_protos_categories_proto_init() {
	if File_app_protos_categories_proto != nil {
		return
	}
	file_app_protos_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_protos_categories_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiltersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_categories_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_protos_categories_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*CategoryResponse_Category)(nil),
		(*CategoryResponse_Status)(nil),
	}
	file_app_protos_categories_proto_msgTypes[3].OneofWrappers = []interface{}{}
	file_app_protos_categories_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*FilterResponse_Filter)(nil),
		(*FilterResponse_Status)(nil),
	}
	file_app_protos_categories_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Filter_RangeFilter)(nil),
		(*Filter_SelectionFilter)(nil),
		(*Filter_BoolFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protos_categories_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_protos_categories_proto_goTypes,
		DependencyIndexes: file_app_protos_categories_proto_depIdxs,
		MessageInfos:      file_app_protos_categories_proto_msgTypes,
	}.Build()
	File_app_protos_categories_proto = out.File
	file_app_protos_categories_proto_rawDesc = nil
	file_app_protos_categories_proto_goTypes = nil
	file_app_protos_categories_proto_depIdxs = nil
}
