// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.1
// source: app/protos/items.proto

package parser

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market     Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
	PageUrl    string  `protobuf:"bytes,2,opt,name=pageUrl,proto3" json:"pageUrl,omitempty"`
	UserQuery  *string `protobuf:"bytes,3,opt,name=userQuery,proto3,oneof" json:"userQuery,omitempty"`
	Params     *string `protobuf:"bytes,4,opt,name=params,proto3,oneof" json:"params,omitempty"`
	NumOfPages *int32  `protobuf:"varint,5,opt,name=numOfPages,proto3,oneof" json:"numOfPages,omitempty"`
}

func (x *ItemsRequest) Reset() {
	*x = ItemsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsRequest) ProtoMessage() {}

func (x *ItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsRequest.ProtoReflect.Descriptor instead.
func (*ItemsRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{0}
}

func (x *ItemsRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

func (x *ItemsRequest) GetPageUrl() string {
	if x != nil {
		return x.PageUrl
	}
	return ""
}

func (x *ItemsRequest) GetUserQuery() string {
	if x != nil && x.UserQuery != nil {
		return *x.UserQuery
	}
	return ""
}

func (x *ItemsRequest) GetParams() string {
	if x != nil && x.Params != nil {
		return *x.Params
	}
	return ""
}

func (x *ItemsRequest) GetNumOfPages() int32 {
	if x != nil && x.NumOfPages != nil {
		return *x.NumOfPages
	}
	return 0
}

type ItemResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*ItemResponse_Item
	//	*ItemResponse_Status
	Message isItemResponse_Message `protobuf_oneof:"message"`
}

func (x *ItemResponse) Reset() {
	*x = ItemResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemResponse) ProtoMessage() {}

func (x *ItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemResponse.ProtoReflect.Descriptor instead.
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{1}
}

func (m *ItemResponse) GetMessage() isItemResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *ItemResponse) GetItem() *Item {
	if x, ok := x.GetMessage().(*ItemResponse_Item); ok {
		return x.Item
	}
	return nil
}

func (x *ItemResponse) GetStatus() *status.Status {
	if x, ok := x.GetMessage().(*ItemResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isItemResponse_Message interface {
	isItemResponse_Message()
}

type ItemResponse_Item struct {
	Item *Item `protobuf:"bytes,1,opt,name=item,proto3,oneof"`
}

type ItemResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*ItemResponse_Item) isItemResponse_Message() {}

func (*ItemResponse_Status) isItemResponse_Message() {}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url      string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ImageUrl string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	IsAdult  bool     `protobuf:"varint,4,opt,name=isAdult,proto3" json:"isAdult,omitempty"`
	Price    float64  `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	OldPrice *float64 `protobuf:"fixed64,6,opt,name=oldPrice,proto3,oneof" json:"oldPrice,omitempty"`
	Rating   *float32 `protobuf:"fixed32,7,opt,name=rating,proto3,oneof" json:"rating,omitempty"`
	Comments *int32   `protobuf:"varint,8,opt,name=comments,proto3,oneof" json:"comments,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Item) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Item) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetOldPrice() float64 {
	if x != nil && x.OldPrice != nil {
		return *x.OldPrice
	}
	return 0
}

func (x *Item) GetRating() float32 {
	if x != nil && x.Rating != nil {
		return *x.Rating
	}
	return 0
}

func (x *Item) GetComments() int32 {
	if x != nil && x.Comments != nil {
		return *x.Comments
	}
	return 0
}

type ItemExtended struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item            *Item             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Characteristics []*Characteristic `protobuf:"bytes,2,rep,name=characteristics,proto3" json:"characteristics,omitempty"`
	Weight          int32             `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *ItemExtended) Reset() {
	*x = ItemExtended{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemExtended) ProtoMessage() {}

func (x *ItemExtended) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemExtended.ProtoReflect.Descriptor instead.
func (*ItemExtended) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{3}
}

func (x *ItemExtended) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemExtended) GetCharacteristics() []*Characteristic {
	if x != nil {
		return x.Characteristics
	}
	return nil
}

func (x *ItemExtended) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type CharacteristicsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market  Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
	ItemUrl string  `protobuf:"bytes,2,opt,name=itemUrl,proto3" json:"itemUrl,omitempty"`
}

func (x *CharacteristicsRequest) Reset() {
	*x = CharacteristicsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacteristicsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacteristicsRequest) ProtoMessage() {}

func (x *CharacteristicsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacteristicsRequest.ProtoReflect.Descriptor instead.
func (*CharacteristicsRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{4}
}

func (x *CharacteristicsRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

func (x *CharacteristicsRequest) GetItemUrl() string {
	if x != nil {
		return x.ItemUrl
	}
	return ""
}

type CharacteristicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*CharacteristicResponse_Characteristic
	//	*CharacteristicResponse_Status
	Message isCharacteristicResponse_Message `protobuf_oneof:"message"`
}

func (x *CharacteristicResponse) Reset() {
	*x = CharacteristicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharacteristicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacteristicResponse) ProtoMessage() {}

func (x *CharacteristicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacteristicResponse.ProtoReflect.Descriptor instead.
func (*CharacteristicResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{5}
}

func (m *CharacteristicResponse) GetMessage() isCharacteristicResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *CharacteristicResponse) GetCharacteristic() *Characteristic {
	if x, ok := x.GetMessage().(*CharacteristicResponse_Characteristic); ok {
		return x.Characteristic
	}
	return nil
}

func (x *CharacteristicResponse) GetStatus() *status.Status {
	if x, ok := x.GetMessage().(*CharacteristicResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isCharacteristicResponse_Message interface {
	isCharacteristicResponse_Message()
}

type CharacteristicResponse_Characteristic struct {
	Characteristic *Characteristic `protobuf:"bytes,1,opt,name=characteristic,proto3,oneof"`
}

type CharacteristicResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*CharacteristicResponse_Characteristic) isCharacteristicResponse_Message() {}

func (*CharacteristicResponse_Status) isCharacteristicResponse_Message() {}

type Characteristic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Value:
	//	*Characteristic_StrValue
	//	*Characteristic_IntValue
	//	*Characteristic_FloatValue
	//	*Characteristic_ListValue
	Value isCharacteristic_Value `protobuf_oneof:"value"`
}

func (x *Characteristic) Reset() {
	*x = Characteristic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Characteristic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Characteristic) ProtoMessage() {}

func (x *Characteristic) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Characteristic.ProtoReflect.Descriptor instead.
func (*Characteristic) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{6}
}

func (x *Characteristic) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Characteristic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Characteristic) GetValue() isCharacteristic_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Characteristic) GetStrValue() string {
	if x, ok := x.GetValue().(*Characteristic_StrValue); ok {
		return x.StrValue
	}
	return ""
}

func (x *Characteristic) GetIntValue() int32 {
	if x, ok := x.GetValue().(*Characteristic_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (x *Characteristic) GetFloatValue() float32 {
	if x, ok := x.GetValue().(*Characteristic_FloatValue); ok {
		return x.FloatValue
	}
	return 0
}

func (x *Characteristic) GetListValue() *StringList {
	if x, ok := x.GetValue().(*Characteristic_ListValue); ok {
		return x.ListValue
	}
	return nil
}

type isCharacteristic_Value interface {
	isCharacteristic_Value()
}

type Characteristic_StrValue struct {
	StrValue string `protobuf:"bytes,3,opt,name=strValue,proto3,oneof"`
}

type Characteristic_IntValue struct {
	IntValue int32 `protobuf:"varint,4,opt,name=intValue,proto3,oneof"`
}

type Characteristic_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,5,opt,name=floatValue,proto3,oneof"`
}

type Characteristic_ListValue struct {
	ListValue *StringList `protobuf:"bytes,6,opt,name=listValue,proto3,oneof"`
}

func (*Characteristic_StrValue) isCharacteristic_Value() {}

func (*Characteristic_IntValue) isCharacteristic_Value() {}

func (*Characteristic_FloatValue) isCharacteristic_Value() {}

func (*Characteristic_ListValue) isCharacteristic_Value() {}

type FiltersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Market      Markets `protobuf:"varint,1,opt,name=market,proto3,enum=app.protos.Markets" json:"market,omitempty"`
	CategoryUrl string  `protobuf:"bytes,2,opt,name=categoryUrl,proto3" json:"categoryUrl,omitempty"`
}

func (x *FiltersRequest) Reset() {
	*x = FiltersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FiltersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FiltersRequest) ProtoMessage() {}

func (x *FiltersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FiltersRequest.ProtoReflect.Descriptor instead.
func (*FiltersRequest) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{7}
}

func (x *FiltersRequest) GetMarket() Markets {
	if x != nil {
		return x.Market
	}
	return Markets_OZON
}

func (x *FiltersRequest) GetCategoryUrl() string {
	if x != nil {
		return x.CategoryUrl
	}
	return ""
}

type FilterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*FilterResponse_Filter
	//	*FilterResponse_Status
	Message isFilterResponse_Message `protobuf_oneof:"message"`
}

func (x *FilterResponse) Reset() {
	*x = FilterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResponse) ProtoMessage() {}

func (x *FilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResponse.ProtoReflect.Descriptor instead.
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{8}
}

func (m *FilterResponse) GetMessage() isFilterResponse_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *FilterResponse) GetFilter() *Filter {
	if x, ok := x.GetMessage().(*FilterResponse_Filter); ok {
		return x.Filter
	}
	return nil
}

func (x *FilterResponse) GetStatus() *status.Status {
	if x, ok := x.GetMessage().(*FilterResponse_Status); ok {
		return x.Status
	}
	return nil
}

type isFilterResponse_Message interface {
	isFilterResponse_Message()
}

type FilterResponse_Filter struct {
	Filter *Filter `protobuf:"bytes,1,opt,name=filter,proto3,oneof"`
}

type FilterResponse_Status struct {
	Status *status.Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*FilterResponse_Filter) isFilterResponse_Message() {}

func (*FilterResponse_Status) isFilterResponse_Message() {}

type Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title        string  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Key          string  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ExternalType string  `protobuf:"bytes,3,opt,name=externalType,proto3" json:"externalType,omitempty"`
	InternalType Filters `protobuf:"varint,4,opt,name=internalType,proto3,enum=app.protos.Filters" json:"internalType,omitempty"`
	// Types that are assignable to Data:
	//	*Filter_RangeFilter
	//	*Filter_SelectionFilter
	//	*Filter_BoolFilter
	Data isFilter_Data `protobuf_oneof:"data"`
}

func (x *Filter) Reset() {
	*x = Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_items_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_items_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_app_protos_items_proto_rawDescGZIP(), []int{9}
}

func (x *Filter) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Filter) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Filter) GetExternalType() string {
	if x != nil {
		return x.ExternalType
	}
	return ""
}

func (x *Filter) GetInternalType() Filters {
	if x != nil {
		return x.InternalType
	}
	return Filters_RANGE
}

func (m *Filter) GetData() isFilter_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *Filter) GetRangeFilter() *RangeFilter {
	if x, ok := x.GetData().(*Filter_RangeFilter); ok {
		return x.RangeFilter
	}
	return nil
}

func (x *Filter) GetSelectionFilter() *SelectionFilter {
	if x, ok := x.GetData().(*Filter_SelectionFilter); ok {
		return x.SelectionFilter
	}
	return nil
}

func (x *Filter) GetBoolFilter() *BoolFilter {
	if x, ok := x.GetData().(*Filter_BoolFilter); ok {
		return x.BoolFilter
	}
	return nil
}

type isFilter_Data interface {
	isFilter_Data()
}

type Filter_RangeFilter struct {
	RangeFilter *RangeFilter `protobuf:"bytes,5,opt,name=rangeFilter,proto3,oneof"`
}

type Filter_SelectionFilter struct {
	SelectionFilter *SelectionFilter `protobuf:"bytes,6,opt,name=selectionFilter,proto3,oneof"`
}

type Filter_BoolFilter struct {
	BoolFilter *BoolFilter `protobuf:"bytes,7,opt,name=boolFilter,proto3,oneof"`
}

func (*Filter_RangeFilter) isFilter_Data() {}

func (*Filter_SelectionFilter) isFilter_Data() {}

func (*Filter_BoolFilter) isFilter_Data() {}

var File_app_protos_items_proto protoreflect.FileDescriptor

var file_app_protos_items_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe2, 0x01, 0x0a, 0x0c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x21, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x88, 0x01, 0x01,
	0x12, 0x1b, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x01, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x88, 0x01, 0x01, 0x12, 0x23, 0x0a,
	0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x50, 0x61, 0x67, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x02, 0x52, 0x0a, 0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x50, 0x61, 0x67, 0x65, 0x73, 0x88,
	0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x6e, 0x75, 0x6d, 0x4f, 0x66, 0x50, 0x61, 0x67, 0x65, 0x73, 0x22, 0x6f, 0x0a, 0x0c, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xfc, 0x01, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x41, 0x64, 0x75, 0x6c,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x64, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x08, 0x6f, 0x6c, 0x64, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x6c, 0x64, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x48, 0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e,
	0x67, 0x88, 0x01, 0x01, 0x12, 0x1f, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x6f, 0x6c, 0x64, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x42, 0x0b, 0x0a,
	0x09, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x92, 0x01, 0x0a, 0x0c, 0x49,
	0x74, 0x65, 0x6d, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x12, 0x44, 0x0a, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x0f, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65,
	0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22,
	0x5f, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x06,
	0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x55, 0x72,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x55, 0x72, 0x6c,
	0x22, 0x97, 0x01, 0x0a, 0x16, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x63,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x48,
	0x00, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69,
	0x63, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x1c, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x20, 0x0a, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x36, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09,
	0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x5f, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x73, 0x52, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x55, 0x72, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x55, 0x72, 0x6c, 0x22, 0x77, 0x0a, 0x0e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x42, 0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xd5, 0x02, 0x0a,
	0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x52, 0x0c,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x47, 0x0a, 0x0f, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x0f, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x38, 0x0a, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x0a, 0x62, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x82, 0x02, 0x0a, 0x0a, 0x49, 0x74, 0x65, 0x6d, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12,
	0x18, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x62, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x43, 0x68, 0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x4e, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x1a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_app_protos_items_proto_rawDescOnce sync.Once
	file_app_protos_items_proto_rawDescData = file_app_protos_items_proto_rawDesc
)

func file_app_protos_items_proto_rawDescGZIP() []byte {
	file_app_protos_items_proto_rawDescOnce.Do(func() {
		file_app_protos_items_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protos_items_proto_rawDescData)
	})
	return file_app_protos_items_proto_rawDescData
}

var file_app_protos_items_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_app_protos_items_proto_goTypes = []interface{}{
	(*ItemsRequest)(nil),           // 0: app.protos.ItemsRequest
	(*ItemResponse)(nil),           // 1: app.protos.ItemResponse
	(*Item)(nil),                   // 2: app.protos.Item
	(*ItemExtended)(nil),           // 3: app.protos.ItemExtended
	(*CharacteristicsRequest)(nil), // 4: app.protos.CharacteristicsRequest
	(*CharacteristicResponse)(nil), // 5: app.protos.CharacteristicResponse
	(*Characteristic)(nil),         // 6: app.protos.Characteristic
	(*FiltersRequest)(nil),         // 7: app.protos.FiltersRequest
	(*FilterResponse)(nil),         // 8: app.protos.FilterResponse
	(*Filter)(nil),                 // 9: app.protos.Filter
	(Markets)(0),                   // 10: app.protos.Markets
	(*status.Status)(nil),          // 11: google.rpc.Status
	(*StringList)(nil),             // 12: app.protos.StringList
	(Filters)(0),                   // 13: app.protos.Filters
	(*RangeFilter)(nil),            // 14: app.protos.RangeFilter
	(*SelectionFilter)(nil),        // 15: app.protos.SelectionFilter
	(*BoolFilter)(nil),             // 16: app.protos.BoolFilter
}
var file_app_protos_items_proto_depIdxs = []int32{
	10, // 0: app.protos.ItemsRequest.market:type_name -> app.protos.Markets
	2,  // 1: app.protos.ItemResponse.item:type_name -> app.protos.Item
	11, // 2: app.protos.ItemResponse.status:type_name -> google.rpc.Status
	2,  // 3: app.protos.ItemExtended.item:type_name -> app.protos.Item
	6,  // 4: app.protos.ItemExtended.characteristics:type_name -> app.protos.Characteristic
	10, // 5: app.protos.CharacteristicsRequest.market:type_name -> app.protos.Markets
	6,  // 6: app.protos.CharacteristicResponse.characteristic:type_name -> app.protos.Characteristic
	11, // 7: app.protos.CharacteristicResponse.status:type_name -> google.rpc.Status
	12, // 8: app.protos.Characteristic.listValue:type_name -> app.protos.StringList
	10, // 9: app.protos.FiltersRequest.market:type_name -> app.protos.Markets
	9,  // 10: app.protos.FilterResponse.filter:type_name -> app.protos.Filter
	11, // 11: app.protos.FilterResponse.status:type_name -> google.rpc.Status
	13, // 12: app.protos.Filter.internalType:type_name -> app.protos.Filters
	14, // 13: app.protos.Filter.rangeFilter:type_name -> app.protos.RangeFilter
	15, // 14: app.protos.Filter.selectionFilter:type_name -> app.protos.SelectionFilter
	16, // 15: app.protos.Filter.boolFilter:type_name -> app.protos.BoolFilter
	0,  // 16: app.protos.ItemParser.GetItems:input_type -> app.protos.ItemsRequest
	4,  // 17: app.protos.ItemParser.GetItemCharacteristics:input_type -> app.protos.CharacteristicsRequest
	7,  // 18: app.protos.ItemParser.GetCategoryFilters:input_type -> app.protos.FiltersRequest
	1,  // 19: app.protos.ItemParser.GetItems:output_type -> app.protos.ItemResponse
	5,  // 20: app.protos.ItemParser.GetItemCharacteristics:output_type -> app.protos.CharacteristicResponse
	8,  // 21: app.protos.ItemParser.GetCategoryFilters:output_type -> app.protos.FilterResponse
	19, // [19:22] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_app_protos_items_proto_init() }
func file_app_protos_items_proto_init() {
	if File_app_protos_items_proto != nil {
		return
	}
	file_app_protos_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_protos_items_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemExtended); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacteristicsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharacteristicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Characteristic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FiltersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_items_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_app_protos_items_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_app_protos_items_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ItemResponse_Item)(nil),
		(*ItemResponse_Status)(nil),
	}
	file_app_protos_items_proto_msgTypes[2].OneofWrappers = []interface{}{}
	file_app_protos_items_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*CharacteristicResponse_Characteristic)(nil),
		(*CharacteristicResponse_Status)(nil),
	}
	file_app_protos_items_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*Characteristic_StrValue)(nil),
		(*Characteristic_IntValue)(nil),
		(*Characteristic_FloatValue)(nil),
		(*Characteristic_ListValue)(nil),
	}
	file_app_protos_items_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*FilterResponse_Filter)(nil),
		(*FilterResponse_Status)(nil),
	}
	file_app_protos_items_proto_msgTypes[9].OneofWrappers = []interface{}{
		(*Filter_RangeFilter)(nil),
		(*Filter_SelectionFilter)(nil),
		(*Filter_BoolFilter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protos_items_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_protos_items_proto_goTypes,
		DependencyIndexes: file_app_protos_items_proto_depIdxs,
		MessageInfos:      file_app_protos_items_proto_msgTypes,
	}.Build()
	File_app_protos_items_proto = out.File
	file_app_protos_items_proto_rawDesc = nil
	file_app_protos_items_proto_goTypes = nil
	file_app_protos_items_proto_depIdxs = nil
}
