// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.1
// source: app/protos/reqHandlerTypes.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PrefType int32

const (
	PrefType_NUM  PrefType = 0
	PrefType_LIST PrefType = 1
)

// Enum value maps for PrefType.
var (
	PrefType_name = map[int32]string{
		0: "NUM",
		1: "LIST",
	}
	PrefType_value = map[string]int32{
		"NUM":  0,
		"LIST": 1,
	}
)

func (x PrefType) Enum() *PrefType {
	p := new(PrefType)
	*p = x
	return p
}

func (x PrefType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PrefType) Descriptor() protoreflect.EnumDescriptor {
	return file_app_protos_reqHandlerTypes_proto_enumTypes[0].Descriptor()
}

func (PrefType) Type() protoreflect.EnumType {
	return &file_app_protos_reqHandlerTypes_proto_enumTypes[0]
}

func (x PrefType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PrefType.Descriptor instead.
func (PrefType) EnumDescriptor() ([]byte, []int) {
	return file_app_protos_reqHandlerTypes_proto_rawDescGZIP(), []int{0}
}

type UserPrefs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key       string      `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Type      PrefType    `protobuf:"varint,2,opt,name=type,proto3,enum=app.protos.PrefType" json:"type,omitempty"`
	NumValue  float64     `protobuf:"fixed64,3,opt,name=numValue,proto3" json:"numValue,omitempty"`
	ListValue *StringList `protobuf:"bytes,4,opt,name=listValue,proto3" json:"listValue,omitempty"`
}

func (x *UserPrefs) Reset() {
	*x = UserPrefs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_reqHandlerTypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserPrefs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPrefs) ProtoMessage() {}

func (x *UserPrefs) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_reqHandlerTypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPrefs.ProtoReflect.Descriptor instead.
func (*UserPrefs) Descriptor() ([]byte, []int) {
	return file_app_protos_reqHandlerTypes_proto_rawDescGZIP(), []int{0}
}

func (x *UserPrefs) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UserPrefs) GetType() PrefType {
	if x != nil {
		return x.Type
	}
	return PrefType_NUM
}

func (x *UserPrefs) GetNumValue() float64 {
	if x != nil {
		return x.NumValue
	}
	return 0
}

func (x *UserPrefs) GetListValue() *StringList {
	if x != nil {
		return x.ListValue
	}
	return nil
}

type ItemExtended struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item        *Item             `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Chars       []*Characteristic `protobuf:"bytes,2,rep,name=chars,proto3" json:"chars,omitempty"`
	TotalWeight int32             `protobuf:"varint,3,opt,name=totalWeight,proto3" json:"totalWeight,omitempty"`
}

func (x *ItemExtended) Reset() {
	*x = ItemExtended{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_reqHandlerTypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemExtended) ProtoMessage() {}

func (x *ItemExtended) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_reqHandlerTypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemExtended.ProtoReflect.Descriptor instead.
func (*ItemExtended) Descriptor() ([]byte, []int) {
	return file_app_protos_reqHandlerTypes_proto_rawDescGZIP(), []int{1}
}

func (x *ItemExtended) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *ItemExtended) GetChars() []*Characteristic {
	if x != nil {
		return x.Chars
	}
	return nil
}

func (x *ItemExtended) GetTotalWeight() int32 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

var File_app_protos_reqHandlerTypes_proto protoreflect.FileDescriptor

var file_app_protos_reqHandlerTypes_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x71,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x1a, 0x16,
	0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x99,
	0x01, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61,
	0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x50, 0x72, 0x65, 0x66, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x75, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x6e, 0x75, 0x6d, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x09, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x88, 0x01, 0x0a, 0x0c, 0x49,
	0x74, 0x65, 0x6d, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x12, 0x30, 0x0a, 0x05, 0x63, 0x68, 0x61, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x43, 0x68,
	0x61, 0x72, 0x61, 0x63, 0x74, 0x65, 0x72, 0x69, 0x73, 0x74, 0x69, 0x63, 0x52, 0x05, 0x63, 0x68,
	0x61, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x57,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x2a, 0x1d, 0x0a, 0x08, 0x50, 0x72, 0x65, 0x66, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x55, 0x4d, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49,
	0x53, 0x54, 0x10, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_protos_reqHandlerTypes_proto_rawDescOnce sync.Once
	file_app_protos_reqHandlerTypes_proto_rawDescData = file_app_protos_reqHandlerTypes_proto_rawDesc
)

func file_app_protos_reqHandlerTypes_proto_rawDescGZIP() []byte {
	file_app_protos_reqHandlerTypes_proto_rawDescOnce.Do(func() {
		file_app_protos_reqHandlerTypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protos_reqHandlerTypes_proto_rawDescData)
	})
	return file_app_protos_reqHandlerTypes_proto_rawDescData
}

var file_app_protos_reqHandlerTypes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_app_protos_reqHandlerTypes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_protos_reqHandlerTypes_proto_goTypes = []interface{}{
	(PrefType)(0),          // 0: app.protos.PrefType
	(*UserPrefs)(nil),      // 1: app.protos.UserPrefs
	(*ItemExtended)(nil),   // 2: app.protos.ItemExtended
	(*StringList)(nil),     // 3: app.protos.StringList
	(*Item)(nil),           // 4: app.protos.Item
	(*Characteristic)(nil), // 5: app.protos.Characteristic
}
var file_app_protos_reqHandlerTypes_proto_depIdxs = []int32{
	0, // 0: app.protos.UserPrefs.type:type_name -> app.protos.PrefType
	3, // 1: app.protos.UserPrefs.listValue:type_name -> app.protos.StringList
	4, // 2: app.protos.ItemExtended.item:type_name -> app.protos.Item
	5, // 3: app.protos.ItemExtended.chars:type_name -> app.protos.Characteristic
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_app_protos_reqHandlerTypes_proto_init() }
func file_app_protos_reqHandlerTypes_proto_init() {
	if File_app_protos_reqHandlerTypes_proto != nil {
		return
	}
	file_app_protos_items_proto_init()
	file_app_protos_types_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_app_protos_reqHandlerTypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserPrefs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_reqHandlerTypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemExtended); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protos_reqHandlerTypes_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_protos_reqHandlerTypes_proto_goTypes,
		DependencyIndexes: file_app_protos_reqHandlerTypes_proto_depIdxs,
		EnumInfos:         file_app_protos_reqHandlerTypes_proto_enumTypes,
		MessageInfos:      file_app_protos_reqHandlerTypes_proto_msgTypes,
	}.Build()
	File_app_protos_reqHandlerTypes_proto = out.File
	file_app_protos_reqHandlerTypes_proto_rawDesc = nil
	file_app_protos_reqHandlerTypes_proto_goTypes = nil
	file_app_protos_reqHandlerTypes_proto_depIdxs = nil
}
