// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v4.25.1
// source: app/protos/types.proto

package parser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Markets int32

const (
	Markets_OZON Markets = 0
)

// Enum value maps for Markets.
var (
	Markets_name = map[int32]string{
		0: "OZON",
	}
	Markets_value = map[string]int32{
		"OZON": 0,
	}
)

func (x Markets) Enum() *Markets {
	p := new(Markets)
	*p = x
	return p
}

func (x Markets) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Markets) Descriptor() protoreflect.EnumDescriptor {
	return file_app_protos_types_proto_enumTypes[0].Descriptor()
}

func (Markets) Type() protoreflect.EnumType {
	return &file_app_protos_types_proto_enumTypes[0]
}

func (x Markets) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Markets.Descriptor instead.
func (Markets) EnumDescriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{0}
}

type Filters int32

const (
	Filters_RANGE          Filters = 0
	Filters_SELECTION      Filters = 1
	Filters_SELECTIONRADIO Filters = 2
	Filters_BOOL           Filters = 3
)

// Enum value maps for Filters.
var (
	Filters_name = map[int32]string{
		0: "RANGE",
		1: "SELECTION",
		2: "SELECTIONRADIO",
		3: "BOOL",
	}
	Filters_value = map[string]int32{
		"RANGE":          0,
		"SELECTION":      1,
		"SELECTIONRADIO": 2,
		"BOOL":           3,
	}
)

func (x Filters) Enum() *Filters {
	p := new(Filters)
	*p = x
	return p
}

func (x Filters) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Filters) Descriptor() protoreflect.EnumDescriptor {
	return file_app_protos_types_proto_enumTypes[1].Descriptor()
}

func (Filters) Type() protoreflect.EnumType {
	return &file_app_protos_types_proto_enumTypes[1]
}

func (x Filters) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Filters.Descriptor instead.
func (Filters) EnumDescriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{1}
}

type RangeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min float64 `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max float64 `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *RangeFilter) Reset() {
	*x = RangeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeFilter) ProtoMessage() {}

func (x *RangeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeFilter.ProtoReflect.Descriptor instead.
func (*RangeFilter) Descriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{0}
}

func (x *RangeFilter) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *RangeFilter) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type SelectionFilterItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SelectionFilterItem) Reset() {
	*x = SelectionFilterItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionFilterItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionFilterItem) ProtoMessage() {}

func (x *SelectionFilterItem) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionFilterItem.ProtoReflect.Descriptor instead.
func (*SelectionFilterItem) Descriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{1}
}

func (x *SelectionFilterItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SelectionFilterItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SelectionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRadio bool                   `protobuf:"varint,1,opt,name=isRadio,proto3" json:"isRadio,omitempty"`
	Items   []*SelectionFilterItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SelectionFilter) Reset() {
	*x = SelectionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SelectionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectionFilter) ProtoMessage() {}

func (x *SelectionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectionFilter.ProtoReflect.Descriptor instead.
func (*SelectionFilter) Descriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{2}
}

func (x *SelectionFilter) GetIsRadio() bool {
	if x != nil {
		return x.IsRadio
	}
	return false
}

func (x *SelectionFilter) GetItems() []*SelectionFilterItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BoolFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *BoolFilter) Reset() {
	*x = BoolFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoolFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolFilter) ProtoMessage() {}

func (x *BoolFilter) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolFilter.ProtoReflect.Descriptor instead.
func (*BoolFilter) Descriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{3}
}

func (x *BoolFilter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_protos_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_app_protos_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_app_protos_types_proto_rawDescGZIP(), []int{4}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_app_protos_types_proto protoreflect.FileDescriptor

var file_app_protos_types_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0x31, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x3f, 0x0a, 0x13, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x62, 0x0a, 0x0f, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x69,
	0x73, 0x52, 0x61, 0x64, 0x69, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73,
	0x52, 0x61, 0x64, 0x69, 0x6f, 0x12, 0x35, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x22, 0x0a, 0x0a,
	0x42, 0x6f, 0x6f, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x24, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x2a, 0x13, 0x0a, 0x07, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74,
	0x73, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x5a, 0x4f, 0x4e, 0x10, 0x00, 0x2a, 0x41, 0x0a, 0x07, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01,
	0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x4c, 0x45, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x52, 0x41, 0x44,
	0x49, 0x4f, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x4f, 0x4f, 0x4c, 0x10, 0x03, 0x42, 0x0f,
	0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_protos_types_proto_rawDescOnce sync.Once
	file_app_protos_types_proto_rawDescData = file_app_protos_types_proto_rawDesc
)

func file_app_protos_types_proto_rawDescGZIP() []byte {
	file_app_protos_types_proto_rawDescOnce.Do(func() {
		file_app_protos_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_protos_types_proto_rawDescData)
	})
	return file_app_protos_types_proto_rawDescData
}

var file_app_protos_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_app_protos_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_app_protos_types_proto_goTypes = []interface{}{
	(Markets)(0),                // 0: app.protos.Markets
	(Filters)(0),                // 1: app.protos.Filters
	(*RangeFilter)(nil),         // 2: app.protos.RangeFilter
	(*SelectionFilterItem)(nil), // 3: app.protos.SelectionFilterItem
	(*SelectionFilter)(nil),     // 4: app.protos.SelectionFilter
	(*BoolFilter)(nil),          // 5: app.protos.BoolFilter
	(*StringList)(nil),          // 6: app.protos.StringList
}
var file_app_protos_types_proto_depIdxs = []int32{
	3, // 0: app.protos.SelectionFilter.items:type_name -> app.protos.SelectionFilterItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_protos_types_proto_init() }
func file_app_protos_types_proto_init() {
	if File_app_protos_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_protos_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionFilterItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SelectionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoolFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_protos_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_protos_types_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_protos_types_proto_goTypes,
		DependencyIndexes: file_app_protos_types_proto_depIdxs,
		EnumInfos:         file_app_protos_types_proto_enumTypes,
		MessageInfos:      file_app_protos_types_proto_msgTypes,
	}.Build()
	File_app_protos_types_proto = out.File
	file_app_protos_types_proto_rawDesc = nil
	file_app_protos_types_proto_goTypes = nil
	file_app_protos_types_proto_depIdxs = nil
}
