# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import categories_pb2 as app_dot_protos_dot_categories__pb2


class CategoryParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRootCategories = channel.unary_stream(
                '/app.protos.CategoryParser/GetRootCategories',
                request_serializer=app_dot_protos_dot_categories__pb2.RootCategoriesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_categories__pb2.CategoryResponse.FromString,
                )
        self.GetSubCategories = channel.unary_stream(
                '/app.protos.CategoryParser/GetSubCategories',
                request_serializer=app_dot_protos_dot_categories__pb2.SubCategoriesRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_categories__pb2.CategoryResponse.FromString,
                )
        self.GetCategoryFilters = channel.unary_stream(
                '/app.protos.CategoryParser/GetCategoryFilters',
                request_serializer=app_dot_protos_dot_categories__pb2.FiltersRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_categories__pb2.FilterResponse.FromString,
                )


class CategoryParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRootCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubCategories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategoryFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CategoryParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRootCategories': grpc.unary_stream_rpc_method_handler(
                    servicer.GetRootCategories,
                    request_deserializer=app_dot_protos_dot_categories__pb2.RootCategoriesRequest.FromString,
                    response_serializer=app_dot_protos_dot_categories__pb2.CategoryResponse.SerializeToString,
            ),
            'GetSubCategories': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSubCategories,
                    request_deserializer=app_dot_protos_dot_categories__pb2.SubCategoriesRequest.FromString,
                    response_serializer=app_dot_protos_dot_categories__pb2.CategoryResponse.SerializeToString,
            ),
            'GetCategoryFilters': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCategoryFilters,
                    request_deserializer=app_dot_protos_dot_categories__pb2.FiltersRequest.FromString,
                    response_serializer=app_dot_protos_dot_categories__pb2.FilterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.protos.CategoryParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CategoryParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRootCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.protos.CategoryParser/GetRootCategories',
            app_dot_protos_dot_categories__pb2.RootCategoriesRequest.SerializeToString,
            app_dot_protos_dot_categories__pb2.CategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSubCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.protos.CategoryParser/GetSubCategories',
            app_dot_protos_dot_categories__pb2.SubCategoriesRequest.SerializeToString,
            app_dot_protos_dot_categories__pb2.CategoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCategoryFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.protos.CategoryParser/GetCategoryFilters',
            app_dot_protos_dot_categories__pb2.FiltersRequest.SerializeToString,
            app_dot_protos_dot_categories__pb2.FilterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
