# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from app.protos import items_pb2 as app_dot_protos_dot_items__pb2


class ItemParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItems = channel.unary_stream(
                '/app.protos.ItemParser/GetItems',
                request_serializer=app_dot_protos_dot_items__pb2.ItemsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_items__pb2.ItemResponse.FromString,
                )
        self.GetItemCharacteristics = channel.unary_stream(
                '/app.protos.ItemParser/GetItemCharacteristics',
                request_serializer=app_dot_protos_dot_items__pb2.CharacteristicsRequest.SerializeToString,
                response_deserializer=app_dot_protos_dot_items__pb2.CharacteristicResponse.FromString,
                )


class ItemParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItemCharacteristics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItems': grpc.unary_stream_rpc_method_handler(
                    servicer.GetItems,
                    request_deserializer=app_dot_protos_dot_items__pb2.ItemsRequest.FromString,
                    response_serializer=app_dot_protos_dot_items__pb2.ItemResponse.SerializeToString,
            ),
            'GetItemCharacteristics': grpc.unary_stream_rpc_method_handler(
                    servicer.GetItemCharacteristics,
                    request_deserializer=app_dot_protos_dot_items__pb2.CharacteristicsRequest.FromString,
                    response_serializer=app_dot_protos_dot_items__pb2.CharacteristicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.protos.ItemParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemParser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.protos.ItemParser/GetItems',
            app_dot_protos_dot_items__pb2.ItemsRequest.SerializeToString,
            app_dot_protos_dot_items__pb2.ItemResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItemCharacteristics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/app.protos.ItemParser/GetItemCharacteristics',
            app_dot_protos_dot_items__pb2.CharacteristicsRequest.SerializeToString,
            app_dot_protos_dot_items__pb2.CharacteristicResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
