# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/protos/types.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61pp/protos/types.proto\x12\napp.protos\"\'\n\x0bRangeFilter\x12\x0b\n\x03min\x18\x01 \x01(\x01\x12\x0b\n\x03max\x18\x02 \x01(\x01\"2\n\x13SelectionFilterItem\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"R\n\x0fSelectionFilter\x12\x0f\n\x07isRadio\x18\x01 \x01(\x08\x12.\n\x05items\x18\x02 \x03(\x0b\x32\x1f.app.protos.SelectionFilterItem\"\x1b\n\nBoolFilter\x12\r\n\x05value\x18\x01 \x01(\t\"\x1c\n\nStringList\x12\x0e\n\x06values\x18\x01 \x03(\t*\x13\n\x07Markets\x12\x08\n\x04OZON\x10\x00*A\n\x07\x46ilters\x12\t\n\x05RANGE\x10\x00\x12\r\n\tSELECTION\x10\x01\x12\x12\n\x0eSELECTIONRADIO\x10\x02\x12\x08\n\x04\x42OOL\x10\x03\x42\x0fZ\rprotos/parserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.protos.types_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rprotos/parser'
  _globals['_MARKETS']._serialized_start=274
  _globals['_MARKETS']._serialized_end=293
  _globals['_FILTERS']._serialized_start=295
  _globals['_FILTERS']._serialized_end=360
  _globals['_RANGEFILTER']._serialized_start=38
  _globals['_RANGEFILTER']._serialized_end=77
  _globals['_SELECTIONFILTERITEM']._serialized_start=79
  _globals['_SELECTIONFILTERITEM']._serialized_end=129
  _globals['_SELECTIONFILTER']._serialized_start=131
  _globals['_SELECTIONFILTER']._serialized_end=213
  _globals['_BOOLFILTER']._serialized_start=215
  _globals['_BOOLFILTER']._serialized_end=242
  _globals['_STRINGLIST']._serialized_start=244
  _globals['_STRINGLIST']._serialized_end=272
# @@protoc_insertion_point(module_scope)
